openapi: 3.0.4
info:
  title: Text Readability Score
  description: Readability Score is a simple tool for calculating the readability score of text. It returns the readability score based on various readability formulas.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/readabilityscore:
    post:
      summary: Calculate Readability Score
      description: Readability Score is a simple tool for calculating the readability score of text. It returns the readability score based on various readability formulas.
      operationId: readabilityscore
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  textCounts:
                    syllableCount: 82
                    lexiconCount: 49
                    sentenceCount: 1
                  readability:
                    fleschReadingEase: 13.28
                    fleschKincaidGrade: 23.6
                    gunningFog: 26.95
                    colemanLiauIndex: 13.19
                    smogIndex: 22.08
                    automatedReadabilityIndex: 27.8
                    daleChallReadabilityScore: 17
                  readabilityText:
                    fleschReadingEase: very confusing
                    daleChallReadabilityScore: average 13th to 15th-grade (college) student
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to calculate the readability score of
                  example: Western astrology is founded on the movements and relative positions of celestial bodies such as the Sun, Moon and planets, which are analysed by their movement through signs of the zodiac (twelve spatial divisions of the ecliptic) and by their aspects (based on geometric angles) relative to one another.
              required:
              - text
              example:
                text: Western astrology is founded on the movements and relative positions of celestial bodies such as the Sun, Moon and planets, which are analysed by their movement through signs of the zodiac (twelve spatial divisions of the ecliptic) and by their aspects (based on geometric angles) relative to one another.
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
